version: "3.1"
services:
  app:
    container_name: conta-corrente-graphql
    restart: always
    build: .
    environment:
      - APP_PORT=8000
      - MONGO_HOST=mongo
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: conta-corrente-mongo
    image: mongo
    ports:
      - "27017:27017"
